#!/bin/bash

echo "🔗 MCP Data Analysis - Local Ollama Connection Helper"
echo "=================================================="
echo ""
echo "This system is now configured to work with your local Ollama!"
echo ""
echo "To connect your local Ollama to this Replit app:"
echo ""
echo "1. 🖥️  On your local machine, start Ollama (listen on all interfaces):"
echo "   OLLAMA_HOST=0.0.0.0:11434 ollama serve"
echo ""
echo "2. 📥 Make sure you have a model installed:"
echo "   ollama pull llama3.2"
echo ""
echo "3. 🌐 Set this environment variable in Replit to your local IP:"
echo "   export OLLAMA_URL=\"http://YOUR_LOCAL_IP:11434\""
echo ""
echo "4. 🚀 Your chat interface will now use your local Ollama!"
echo ""
echo "Example local IPs:"
echo "   - If on same network: http://192.168.1.xxx:11434"  
echo "   - If using localhost tunneling: http://localhost:11434"
echo ""
echo "Note: The system automatically checks the OLLAMA_URL environment"
echo "variable and falls back to localhost:11434 if not set."
echo ""
echo "Happy analyzing! 🎉"